services:
  - type: web
    name: evara-ai
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 300 --preload
    envVars:
      - key: GEMINI_API_KEY
        sync: false
